language: node_js

node_js:
  - 12.18.1

before_script:
  - yarn

script:
  - yarn build

deploy:
  local_dir: dist
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  on:
    branch: master
