language: node_js

node_js:
  - 12.18.1

root:
  os: linux
  dist: xenial

before_script:
  - npm install

jobs:
  include:
    - stage: build
      script:
        - npm run build
        # - npm test

    - stage: deploy
      script: skip
      deploy:
        local_dir: dist
        provider: pages
        token: $GITHUB_TOKEN
        on:
          branch: master
