language: node_js

node_js:
  - 12.18.1

cache: 
  yarn: true
  directories:
    - dist
    - node_modules

before_script:
  - yarn

jobs:
  include:
    - stage: build
      script:
        - yarn build

    - stage: deploy
      script:
        # use custom domain for github pages
        - echo $CUSTOM_DOMAIN > dist/CNAME
      deploy:
        local_dir: dist
        provider: pages
        skip_cleanup: true
        token: $GITHUB_TOKEN
        on:
          branch: master
