version: 2.1

orbs:
  node: circleci/node@2.0.3
  gh-pages: sugarshin/gh-pages@0.0.6

executors:
  node_v12:
    docker:
      - image: node:12.18-alpine
    working_directory: /app

jobs:
  build:
    executor: node_v12
    steps:
      - checkout
      - node/install-packages:
          app-dir: /app
          pkg-manager: yarn
          cache-key: yarn.lock
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy_ghpages:
    executor: node_v12
    steps:
      - run: apk --no-cache add bash ca-certificates git openssh
      - attach_workspace:
          at: /app
      - run:
          name: Install custom domain
          command: echo "monistra.clgt.io" > dist/CNAME
      - gh-pages/deploy:
          build-dir: dist
          ssh-fingerprints: $FINGERPRINTS

workflows:
  version: 2.0
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy_ghpages:
          requires:
            - build
